name: Sync Veiculos Valle

on:
  schedule:
    - cron: "0 13 * * 1-5"   # 10:00 Brasil
    - cron: "0 20 * * 1-5"   # 17:00 Brasil
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      TOKEN_BASE: ${{ secrets.TOKEN_BASE }}
      USUARIO_API: ${{ secrets.USUARIO_API }}
      SENHA_API: ${{ secrets.SENHA_API }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CODIGO_COOPERATIVA: ${{ secrets.CODIGO_COOPERATIVA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests psycopg2-binary

      - name: Run script
        run: python sync_veiculos.py
